Feature b
ldelbel/apple-webpage-clone pull request #1
Opened 2020-05-11 17:15 UTC by ldelbel

In this project I learned about gradients and advanced styling tools and resources, applying it in details to achieve my goal of making an apple's webpage clone. The page that was cloned is found in this link: https://web.archive.org/web/20140301004610/http://www.apple.com/ 

In this project I practiced the following topics:

- Image embedding and background image handling
- Gradient application to achieve specific visual effects
- Mixed positioning techniques to work together
- Media queries to handle responsiveness

Notes:
       - The version of the webpage that I cloned is the one I have opened in the Brave browser inside Windows. It differs in some details from the one I opened in Firefox inside Xubuntu.
       - My HTML Validator is showing a warning about Unicode Private Use Area (Charmod C073). I made some research about it, and found out there is no solution but changing all the method of including the icon to remove that warning. Because it's a warning and a non-fixable one, I chose to keep it there. Let me know if I need to change the method.

2020-05-11 22:07 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo (TSE)

2020-05-11 22:09 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi @ldelbel, congratulations on the effort you put on this project :+1: Nice work :smiley: PR has a title and a description and README looks professional :smile: Let us improve our code and make it even better by addressing the comments below:
- Kindly enable stickler by visiting stickler-ci.com
- There is a horizontal scroll that needs to be fixed. Kindly check the image and see how it appears
![work1](https://user-images.githubusercontent.com/46388113/81616387-e4d80900-93d2-11ea-8ef4-41f92c9ae26b.png)
- Since this project is primarily based on using backgrounds and gradients, let us use background-images for this part of the code
![work](https://user-images.githubusercontent.com/46388113/81616274-b9edb500-93d2-11ea-8676-b55333600c33.png)
- There are some repeating codes in our CSS file, let us apply the DRY rule. Kindly check this [article](https://speckyboy.com/good-bad-css-practices/)
- W3validator returned 1 warning, it is easily fixable, kindly address it

Kindly make these changes and submit another code review :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2020-05-12 09:39 UTC, ldelbel commented
About the warning in HTML Validator, it seems there is no simple solution for this problem. I would probably need to change my solution for inseting the icon. For more info https://stackoverflow.com/questions/23978976/fontawesome-usage-displeases-w3c-validator 

I want to know if I really need to change it, because it's a good solution in my point of view.

2020-05-12 11:00 UTC, christianotieno requested changes
## Hello @ldelbel 👋 
Everything looks good. There some tiny bits of changes left before we wrap this up.
- - [ ] Note that the page need not be having a scroll. A `100` for `view height` and  `view width` would suffice in this case.
- - [ ] Also note that the four elements should be links (to other articles or `#`) ([link to page](https://web.archive.org/web/20140301004610/http://www.apple.com/)).  

- - [ ] In the README, kindly add some instructions on how to best clone the project and use it, thank you.

♻️ Work on these changes and resubmit another CRR, thank you.

Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

2020-05-12 16:48 UTC, rammazzoti2000 approved these changes
### Hello @ldelbel you did great with the project :1st_place_medal: 
#### The project looks great. Good job for implementing the required changes.
### Project Approved :tada: :rocket: 
Before merging, to avoid a new review request, please fix the issue mentioned by the previous tse regarding the horizontal overflow.
- [ ] Change .thumb width to remove the overflow
```
.thumb {
    width: 24.7vw;
}
```
Cheers and Happy coding! :clap: 

##### Code review by Alexandru Bangau

(Feel free to contact me on slack by the handle of alexandru if you have any additional question)</em>

### :heavy_check_mark:   Status: Approved.

2020-05-12 16:48 UTC, rammazzoti2000 commented on styles.css
> +  width: 25vw;
You still have the horizontal overflow, caused by the width of .thumbs, change the width to` width: 24.7vw;`

2020-05-12 16:49 UTC, rammazzoti2000 approved these changes
### :heavy_check_mark: Status: Approved

2020-05-12 17:17 UTC, merged